apiVersion: v1
kind: Service
metadata:
  labels:
    app: redissvc
  name: {{ .Values.redissvc.name }}
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: {{ .Values.redissvc.port }}
    targetPort: {{ .Values.redissvc.port }}
  selector:
    app: redissvc
