apiVersion: v1
kind: Service
metadata:
  labels:
    app: resultsvc
  name: {{ .Values.resultsvc.name }}
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: {{ .Values.resultsvc.port }}
    targetPort: 80
    nodePort: {{ .Values.resultsvc.nodePort }}
  selector:
    app: resultsvc
