apiVersion: v1
kind: Service
metadata:
  labels:
    app: votesvc
  name: {{ .Values.votesvc.name }}
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: {{ .Values.votesvc.port }}
    targetPort: {{ .Values.votesvc.targetPort }}
    nodePort: {{ .Values.votesvc.nodePort }}
  selector:
    app: vote-svc
